# This file was generated by GoReleaser. DO NOT EDIT.
cask "ssdev-cairn" do
  version "1.0.2"

  on_macos do
    on_arm do
      sha256 "c73e9091c72caf922fb1a6b472aec1c7e81ec04eb50defe96d9fad0dff399350"
      url "https://github.com/ssdev-labs/homebrew-tap/releases/download/ssdev-cairn-v#{version}/ssdev-cairn_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d3f479f0481ea93724a846e2e5975e934a9671e2283984936e0f0f152d68893b"
      url "https://github.com/ssdev-labs/homebrew-tap/releases/download/ssdev-cairn-v#{version}/ssdev-cairn_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6ad83f23b94c83fbd4648710e97a0df5efe0bc04de8fb02f4cf72f017a28f2a6"
      url "https://github.com/ssdev-labs/homebrew-tap/releases/download/ssdev-cairn-v#{version}/ssdev-cairn_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "240f6414f244739980b80a2b37e8db63d9aa7ae5b076e59d88674c4207548cdd"
      url "https://github.com/ssdev-labs/homebrew-tap/releases/download/ssdev-cairn-v#{version}/ssdev-cairn_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ssdev-cairn"
  desc "Add local AI coding context to Git commit messages"
  homepage "https://github.com/ssdev-labs/homebrew-tap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-cairn"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-cairn"] if OS.mac?
  end

  zap script: {
    executable: "#{staged_path}/git-cairn",
    args:       ["uninstall", "--all"],
  }
end
