# This file was generated by GoReleaser. DO NOT EDIT.
cask "ssdev-cairn" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "ddef20b70ae80d36419af9e19adb4bd2951dc5f95dc84b0493f58423929a8d30"
      url "https://github.com/yahuo/homebrew-tap/releases/download/ssdev-cairn-v#{version}/ssdev-cairn_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f94e05d886af478a0b7886a9da5a48fd97b73080fef333a1a4886addd7c75d3f"
      url "https://github.com/yahuo/homebrew-tap/releases/download/ssdev-cairn-v#{version}/ssdev-cairn_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1efe9dab8ff8a34e6d72755196512a061c16e7bffa71d4d7c55e8ce99c55c202"
      url "https://github.com/yahuo/homebrew-tap/releases/download/ssdev-cairn-v#{version}/ssdev-cairn_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6c0cd45df9ba08dd52f78dd699b4cc19baf708c08b780b4ddf4af75ecb891e8b"
      url "https://github.com/yahuo/homebrew-tap/releases/download/ssdev-cairn-v#{version}/ssdev-cairn_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ssdev-cairn"
  desc "Add local AI coding context to Git commit messages"
  homepage "https://github.com/yahuo/homebrew-tap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-cairn"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-cairn"] if OS.mac?
  end

  # No zap stanza required
end
